-- Insert 5 test properties with luxury real estate data
INSERT INTO public.properties (
  title, 
  description, 
  price, 
  location, 
  bedrooms, 
  bathrooms, 
  square_feet, 
  lot_size, 
  property_type, 
  status, 
  images, 
  amenities, 
  features, 
  year_built,
  agent
) VALUES 
(
  'Luxury Penthouse Victoria Island',
  'Stunning 4-bedroom penthouse with panoramic views of Lagos lagoon. Premium finishes throughout with marble floors, Italian kitchen, and private elevator access.',
  850000000,
  'Victoria Island, Lagos',
  4,
  5,
  3500,
  '500 sqm',
  'Penthouse',
  'available',
  ARRAY['https://images.unsplash.com/photo-1721322800607-8c38375eef04?w=800&h=600&fit=crop'],
  ARRAY['Private Elevator', 'Marble Floors', 'Italian Kitchen', 'Panoramic Views', 'Balcony', 'Parking'],
  ARRAY['Smart Home System', 'Central AC', 'Security System', 'Generator'],
  2023,
  '{"name": "John Smith", "phone": "+234 801 234 5678", "email": "john@mansaluxe.com"}'::jsonb
),
(
  'Modern Villa Lekki Phase 1',
  'Contemporary 5-bedroom villa with smart home features and private pool in gated community. Perfect for luxury family living.',
  420000000,
  'Lekki Phase 1, Lagos',
  5,
  6,
  4500,
  '800 sqm',
  'Villa',
  'available',
  ARRAY['https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop'],
  ARRAY['Private Pool', 'Smart Home', 'Gated Community', 'Garden', '2-Car Garage', 'Security'],
  ARRAY['Swimming Pool', 'Home Automation', 'CCTV', 'Backup Generator'],
  2022,
  '{"name": "Sarah Johnson", "phone": "+234 802 345 6789", "email": "sarah@mansaluxe.com"}'::jsonb
),
(
  'Executive Duplex Ikoyi',
  'Elegant 4-bedroom duplex in prestigious Ikoyi neighborhood with garden and 2-car garage. Classic architecture meets modern luxury.',
  320000000,
  'Ikoyi, Lagos',
  4,
  4,
  2800,
  '400 sqm',
  'Duplex',
  'available',
  ARRAY['https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&h=600&fit=crop'],
  ARRAY['Garden', '2-Car Garage', 'Prestigious Location', 'Classic Design', 'Security'],
  ARRAY['Landscaped Garden', 'Modern Kitchen', 'Master Suite', 'Study Room'],
  2021,
  '{"name": "Michael Brown", "phone": "+234 803 456 7890", "email": "michael@mansaluxe.com"}'::jsonb
),
(
  'Waterfront Mansion Banana Island',
  'Exclusive 6-bedroom mansion with private jetty and helipad. Ultimate luxury living with water views and premium amenities.',
  1200000000,
  'Banana Island, Lagos',
  6,
  8,
  8000,
  '1200 sqm',
  'Mansion',
  'available',
  ARRAY['https://images.unsplash.com/photo-1494891848038-7bd202a2afeb?w=800&h=600&fit=crop'],
  ARRAY['Private Jetty', 'Helipad', 'Water Views', 'Premium Finishes', 'Wine Cellar', 'Home Theater'],
  ARRAY['Waterfront Access', 'Luxury Fittings', 'Multiple Living Areas', 'Staff Quarters'],
  2024,
  '{"name": "Elizabeth Davis", "phone": "+234 804 567 8901", "email": "elizabeth@mansaluxe.com"}'::jsonb
),
(
  'Luxury Apartment Eko Atlantic',
  'Modern 3-bedroom apartment with city views in prestigious Eko Atlantic development. Contemporary living at its finest.',
  280000000,
  'Eko Atlantic, Lagos',
  3,
  3,
  1800,
  '200 sqm',
  'Apartment',
  'available',
  ARRAY['https://images.unsplash.com/photo-1472396961693-142e6e269027?w=800&h=600&fit=crop'],
  ARRAY['City Views', 'Modern Design', 'Prestigious Development', 'Concierge Service', 'Gym Access'],
  ARRAY['Floor-to-Ceiling Windows', 'Modern Kitchen', 'Built-in Wardrobes', 'Balcony'],
  2023,
  '{"name": "David Wilson", "phone": "+234 805 678 9012", "email": "david@mansaluxe.com"}'::jsonb
);